services:
  postgres:
    image: postgres:16.2
    volumes:
    - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: active_lobbies
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

volumes:
  postgres_data: {}
